version: "3.9"
services:
  py3:
    build:
      context: ./
      dockerfile: Dockerfile
    image: koki-shimizu_swindn
    container_name: Dual-Norm
    shm_size: "100gb"
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    volumes:
      - /home/koki-shimizu/data:/works/data
      - /home/koki-shimizu/models/Dual-Normalization:/works/model

    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ["1"]
              capabilities: [gpu]